### ISSUE TITLE
2) MVP List

### ISSUE THREAD

**Issue by jtom2388** [cdellacqua123/PaperTrader#2]
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

**Comment by jtom2388** [comment]
- Provide details on each MVP (2 to 3 bullet points)
- Add an estimated timeline for each MVP

**Comment by cdellacqua123** [comment]
I think I got everything! Lmk if there's anything I should change or is missing!

**Comment by jtom2388** [comment]
Looks good. Just swap your MVP 4 and 5. They're out of order

**Comment by cdellacqua123** [comment]
Got it! Thanks!
